# Generated by Django 3.2.9 on 2022-07-15 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymanager',
            name='manager_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_manager_manager_user', to='accounts.manageruser'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='normal_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_normal_user', to='accounts.normaluser'),
        ),
        migrations.AlterField(
            model_name='manageruser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager_user_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='normal_user_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='normal_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specialist_normal_user', to='accounts.normaluser'),
        ),
        migrations.AlterField(
            model_name='technicalmanager',
            name='manager_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technical_manager_manger_user', to='accounts.manageruser'),
        ),
    ]
