# Generated by Django 3.2.9 on 2022-08-05 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220718_0014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companymanager',
            options={'verbose_name': 'مدیر شرکت', 'verbose_name_plural': 'مدیران شرکت'},
        ),
        migrations.AlterModelOptions(
            name='manageruser',
            options={'verbose_name': 'کاربر مدیر', 'verbose_name_plural': 'کاربران مدیر'},
        ),
        migrations.AlterModelOptions(
            name='normaluser',
            options={'verbose_name': 'کاربر عادی', 'verbose_name_plural': 'کاربران عادی'},
        ),
        migrations.AddField(
            model_name='specialist',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
