# Generated by Django 3.2.9 on 2022-08-12 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220805_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciality',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounts.speciality'),
        ),
    ]
