# Generated by Django 3.2.9 on 2022-08-18 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_speciality_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normaluser',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
