version: "3.9"

services:
   arno:
      build:
         context: .
         dockerfile: Dockerfile
      # command: bash -c "python manage.py collectstatic  --noinput && gunicorn -c gunicorn.conf.py"
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
         - .:/app
      ports:
         - 8000:8000
      env_file:
         - .env
      restart: "on-failure"
      depends_on:
         - postgres-db
      networks:
         - core


   postgres-db:
      image: kartoza/postgis:12.1
      ports:
         - 5432:5432
      volumes:
         - postgres_data:/var/lib/postgresql
      environment:
         - POSTGRES_USER=${POSTGRES_USER}
         - POSTGRES_PASS=${POSTGRES_PASS}
         - POSTGRES_DBNAME=${POSTGRES_DBNAME}
      restart: "on-failure"
      networks:
         - core


networks:
   core:
      name: core
      driver: bridge

volumes:
   postgres_data: null
