# Generated by Django 3.2.9 on 2022-08-02 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220718_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('PEND', 'pending'), ('WAIC', 'Waiting for acceptance of customer from specialist'), ('WAIS', 'Waiting for acceptance of the specialist from customer'), ('PROG', 'In Progress'), ('DONE', 'Done'), ('CNCL', 'Canceled'), ('REJC', 'Rejected')], default='PEND', max_length=4),
        ),
    ]
