# Generated by Django 3.2.9 on 2022-08-05 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('PEND', 'در حال بررسی'), ('WAIC', 'منتظر پذیرش مشتری از سوی متخصص'), ('WAIS', 'منتظر پذیرش متخصص از سوی مشتری'), ('PROG', 'در حال انجام'), ('DONE', 'انجام شده'), ('CNCL', 'لغو شده'), ('REJC', 'رد شده')], default='PEND', max_length=4),
        ),
    ]
