# Generated by Django 3.2.9 on 2022-07-15 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('user_type', models.CharField(choices=[('CM', 'Company Manager'), ('TM', 'Technical Manager'), ('C', 'Customer'), ('S', 'Specialist')], default=[('CM', 'Company Manager'), ('TM', 'Technical Manager'), ('C', 'Customer'), ('S', 'Specialist')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='SystemFeedbackReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.technicalmanager')),
            ],
        ),
        migrations.CreateModel(
            name='SystemFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('T', 'Technical'), ('O', 'Other')], default='O', max_length=1)),
                ('status', models.CharField(choices=[('N', 'New'), ('V', 'Viewed'), ('R', 'Replied')], default='N', max_length=1)),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback.systemfeedbackreply')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.normaluser')),
            ],
        ),
        migrations.CreateModel(
            name='MetricScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.evaluationmetric')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metric_scores', models.ManyToManyField(blank=True, null=True, to='feedback.MetricScore')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.request')),
            ],
        ),
    ]
