# Generated by Django 3.2.9 on 2022-08-04 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220718_0014'),
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.normaluser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evaluationmetric',
            name='user_type',
            field=models.CharField(choices=[('CM', 'Company Manager'), ('TM', 'Technical Manager'), ('C', 'Customer'), ('S', 'Specialist')], default='C', max_length=2),
        ),
    ]
