# Generated by Django 3.2.9 on 2022-08-13 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20220804_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metricscore',
            name='user',
        ),
    ]
