# Generated by Django 3.2.9 on 2022-08-18 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_alter_feedback_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScorePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_score', models.FloatField()),
                ('allowed_requests', models.IntegerField()),
            ],
        ),
    ]
