# Generated by Django 3.2.9 on 2022-08-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_scorepolicy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemfeedback',
            name='type',
            field=models.CharField(choices=[('T', 'Technical'), ('C', 'Complaint'), ('S', 'Suggestion'), ('O', 'Other')], default='O', max_length=1),
        ),
    ]
